title: SafeTravel
url: https://safetravel.ica.gov.sg
favicon: /images/favicon-stp.svg
notification: null
colors:
  primary-color: "#C35152"
  secondary-color: "#C35152"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
description: test test
staging: https://govtech-stp-staging.netlify.app
prod: https://govtech-stp-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
resources_name: News-and-Media
